### ISSUE TITLE
I would like to add a feature to monitor replication lag (Seconds_Behind_Master) and return a 500 error if it exceeds the threshold

### ISSUE THREAD

**Issue by rnakamine** [fujiwara/mysql-slave-healthcheck-agent#1]
Hello,

First, thank you for creating such great software.

I want to propose a new feature to enhance the MySQL replication monitoring functionality of this software. Specifically, I suggest adding the ability to monitor the replication lag (Seconds_Behind_Master) and return a 500 error if the lag exceeds a specified threshold.

### Feature Details:

`-max-seconds-behind-master`: This flag will allow users to set the maximum acceptable replication lag (in seconds). If the Seconds_Behind_Master exceeds this value, the application will return a 500 error.

This feature would be highly beneficial for users who must ensure their replication lag remains within acceptable limits.

If this approach sounds good, I would be happy to create a pull request for it.

Thank you for considering this proposal. I look forward to your feedback.

**Comment by rnakamine** [comment]
I apologize for the confusion. We need to monitor the value of `Seconds_Behind_Master`, not `SQL_Delay`.

**Comment by fujiwara** [comment]
@rnakamine Thank you for your suggestion! I haven't used this project for many years, so I don't have the motivation to make changes. Please feel free to fork the repository and modify it as needed.

**Comment by rnakamine** [comment]
@fujiwara Thank you for your response and for confirming. I understand. I will fork the repository and make the necessary modifications.
